% deterministic polynomial policy function
function [action, actionphi_pos, actionphi_neg] = ...
    policy_function_deterministic(tau, asample)
    % input : 
    % tau : policy index parameter 
    % sample, K, L
    % output:
    % action : action under the policy index
    % actionphi_pos: radial basis function corresponding to that action wrt positive reward
    % actionphi_neg: radial basis function corresponding to that action wrt negative reward
    % in_pol = [1, asample.state_pos, asample.state_pos^2, asample.state_neg, ...
    %            asample.state_neg^2, asample.state_pos*asample.state_neg]*tau;
    in_pol = [ 1, asample.state_pos, asample.state_pos^2, ...
                     asample.state_neg, asample.state_neg^2, ...
                     asample.state_neg*asample.state_pos ]*tau;
    action = (in_pol < 1)*1 + ...
                (in_pol >= 1 && in_pol < 2)*2 + ...
                (in_pol >= 2 && in_pol < 3)*3 + ...
                (in_pol >= 3 && in_pol < 4)*4 + ...
                (in_pol >= 4)*5;
    actionphi_pos = basis_fast(asample.state_pos, action, asample.prctile_state_pos, ...
                          asample.dist_state_pos);
    actionphi_neg = basis_fast(asample.state_neg, action, asample.prctile_state_neg, ...
                          asample.dist_state_neg);
  % disp(action);
end

