%-------------------------------------
% feature construction for Q functions
% input is a single sample
%-------------------------------------
function phi = feature ( m, w, d, f, med_m, med_w, k)
    cnst_m = 0.05;
    cnst_w = 0.025;
    if ( f == 1 )
        % absorb state
        phi = zeros(k, 1);
    else
        phi = [ 1;... 
                exp( -cnst_m * (m - med_m)^2); ...
                exp( -cnst_w * (w - med_w)^2); ...
                d; ...
                d^2; ...
                d * exp( -cnst_m * (m - med_m)^2); ...
                d * exp( -cnst_w * (w - med_w)^2);...
                d^2 * exp( -cnst_m * (m - med_m)^2); ...
                d^2 * exp( -cnst_w * (w - med_w)^2) ];
    end
end